CI: Add ShellCheck action (#15)
* Disable SC2086

* Fix lint errors

* Add ShellCheck action

Co-authored-by: Lefteris Garyfalakis <lefterisgar@gmail.com>

diff --git a/limoji b/limoji
--- a/limoji
+++ b/limoji
@@ -3,9 +3,9 @@
 
 readonly VERSION="0.1.0"
 
-parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
+parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit ; pwd -P )
 
-cd "$parent_path"
+cd "$parent_path" || exit
 
 # A few values so the script can run in color
 COL_NC='\e[0m' # No Color
@@ -21,7 +21,7 @@ QUESTION="${COL_NC}[${COL_LIGHT_BLUE}?${COL_NC}]"
 # A function that copies the selected emoticon to the clipboard
 # Works on both X11 and Wayland
 copyToClipboard() {
-    if [ $XDG_SESSION_TYPE == "x11" ]; then
+    if [ "$XDG_SESSION_TYPE" == "x11" ]; then
         xclip -selection c
     else
         wl-copy
@@ -31,7 +31,7 @@ copyToClipboard() {
 # Function that picks a random emoticon name
 fetchRandomName() {
     # Generate a random number between 1 and ascii line count
-    randomLine=$(( 1 + $RANDOM % $(wc -l ascii | awk '{print $1}') ))
+    randomLine=$(( 1 + RANDOM % $(wc -l ascii | awk '{print $1}') ))
 
     # Fetch emoticon's name from the selected line
     randomName=$(head -$randomLine ascii | tail +$randomLine | cut -d= -f1)
@@ -47,11 +47,12 @@ randomEmoticon() {
     done
 
     # Finally print the emoticon and copy it to the clipboard
-    printf  "%b %b$randomName was copied to the clipboard successfully:%b\\n" "${TICK}" "${COL_LIGHT_GREEN}" "${COL_NC}"
+    printf "%b %b$randomName was copied to the clipboard successfully:%b\n" "${TICK}" "${COL_LIGHT_GREEN}" "${COL_NC}"
+    # shellcheck disable=SC2086 # Intended splitting
     echo -e ${!randomName} | tee >(copyToClipboard)
 
     #Ask the user if he wants another emoticon
-    printf "%b %bDo you want another one? (y/n) %b" "${QUESTION}"
+    printf "%b Do you want another one? (y/n) " "${QUESTION}"
     read -n 1 -r
     printf "\n"
 }
@@ -60,33 +61,33 @@ randomEmoticon() {
 set -f
 
 # Fetch all emoticons from the file
-. ascii
+source ascii
 
 # Check if current session is X11
-if [ $XDG_SESSION_TYPE == "x11" ]; then
+if [ "$XDG_SESSION_TYPE" == "x11" ]; then
     # Verify xclip has been installed
     if ! hash xclip 2> /dev/null; then
-        printf "%b %bX11 detected%b\\n" "${INFO}"
-        printf "%b %bxclip is required for copying text to the clipboard%b\\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
+        printf "%b X11 detected\n" "${INFO}"
+        printf "%b %bxclip is required for copying text to the clipboard%b\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
         exit 2
     fi
 # Otherwise it is Wayland
 else
     # Verify wl-clipboard has been installed
     if ! hash wl-copy 2> /dev/null; then
-        printf "%b %bWayland detected%b\\n" "${INFO}"
-        printf "%b %bwl-clipboard is required for copying text to the clipboard%b\\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
+        printf "%b Wayland detected\n" "${INFO}"
+        printf "%b %bwl-clipboard is required for copying text to the clipboard%b\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
         exit 2
     fi
 fi
 
 # Detect number of arguments
 if [ $# == 1 ]; then
-    if [ $1 == --emoticons ]; then
+    if [ "$1" == --emoticons ]; then
         echo -e "$(cat ./ascii)"
-    elif [ $1 == --help ]; then
+    elif [ "$1" == --help ]; then
         echo -e "Usage: limoji <emoticon>\nlimoji --random   Print a random emoticon\nlimoji --emoticon Show a list of the available emoticons\nlimoji --version  Display Limoji's version\nlimoji --help	  Show this list\n\nFor more information you can visit our GitHub repository: https://github.com/GEROGIANNIS/Limoji"
-    elif [ $1 == --random ]; then
+    elif [ "$1" == --random ]; then
         # Picks a random emoticon
         randomEmoticon
 
@@ -94,23 +95,24 @@ if [ $# == 1 ]; then
         while [[ $REPLY =~ ^[Yy]$ ]]; do
             randomEmoticon
         done
-    elif [ $1 == --version ]; then
-        printf "Limoji ${VERSION}\n"
+    elif [ "$1" == --version ]; then
+        printf "Limoji %s\n" "${VERSION}"
     else
         # Convert all uppercase characters to lowercase
-        set $(echo $1 | tr '[:upper:]' '[:lower:]')
+        set "$(echo "$1" | tr '[:upper:]' '[:lower:]')"
 
         # Check if the selected emoticon exists
         if ! test -z "${!1}"; then
-            printf  "%b %b$1 was copied to the clipboard successfully:%b\\n" "${TICK}" "${COL_LIGHT_GREEN}" "${COL_NC}"
+            printf "%b %b$1 was copied to the clipboard successfully:%b\n" "${TICK}" "${COL_LIGHT_GREEN}" "${COL_NC}"
+            # shellcheck disable=SC2086 # Intended splitting
             echo -e ${!1} | tee >(copyToClipboard)
         else
-            printf "%b %bThe specified emoji doesn't exist!%b\\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
+            printf "%b %bThe specified emoji doesn't exist!%b\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
             printf "Try 'limoji --emoticons' for a list of available emojis.\n"
         fi
     fi
 else
-    printf "%b %bInvalid argument!%b\\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
+    printf "%b %bInvalid argument!%b\n" "${CROSS}" "${COL_LIGHT_RED}" "${COL_NC}"
     printf "Try 'limoji --help' for a list of available commands.\n"
 fi
 
